[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pdfparser"
version = "0.1.0"
description = "Fast bank statement PDF parser"
dependencies = ["pdfplumber"]

[tool.setuptools.packages.find]
where = ["."]
